[package]
name = "warrah"
version = "0.1.0"
edition = "2021"
description = "Warrah: A CLI tool and library that naively removes code comments from a text file with the goal of feeding the result to an LLM."
license = "Unlicense"
repository = "https://github.com/evgenyneu/warrah"
readme = "README.md"
homepage = "https://github.com/evgenyneu/warrah"
documentation = "https://docs.rs/warrah"
keywords = ["text", "CLI", "LLM"]
categories = ["command-line-utilities", "text-processing"]

[dependencies]


[dev-dependencies]


[lib]
name = "warrah"
path = "src/lib.rs"

[[bin]]
name = "warrah"
path = "src/main.rs"

[profile.release]
# Settings to make release binary smaller: https://github.com/johnthagen/min-sized-rust
strip = true # Automatically strip symbols from the binary.
opt-level = "z" # Optimize for size.
lto = true # Enable Link Time Optimization
codegen-units = 1 # Reduce Parallel Code Generation
