# This is a single line comment in Makefile

# This is another single line comment
# with multiple lines
# of comments

# This is a comment before a target
target1:
	@echo "This is a command"
	# This is a comment after a command

# This is a comment before another target
target2: target1
	@echo "This is another command"
	# This is another comment after a command

# This is a comment before a variable
VAR = value

# This is a comment before a rule
%.o: %.c
	@echo "Compiling $<"
	# This is a comment in a pattern rule
