name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Cargo Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: rust-lang/setup-rust@v1
        with:
          rust-version: stable

      - name: Run tests
        run: cargo test --workspace
        env:
          CI: true
